version: '3.8'

secrets:
  jetbrains_user_pubkey:
    file: ${JETBRAINS_USER_PUBKEY}

services:
  ehr_adversarial_attack:
    env_file:
      - .env
    image: duanegoodner/dev_envs:ehr_aa_app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    secrets:
      - jetbrains_user_pubkey
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - PRIMARY_USER=${PRIMARY_USER}
        - JETBRAINS_USER=${JETBRAINS_USER}
        - WORK_GROUP=${WORK_GROUP}
        - CONTAINER_DEVSPACE=${CONTAINER_DEVSPACE}
        - CONTAINER_PROJECT_ROOT=${CONTAINER_PROJECT_ROOT}
      secrets:
        - jetbrains_user_pubkey
    container_name: ehr_aa_app
    entrypoint:
       [
        "/bin/bash",
        "/usr/local/entrypoints/jbs/main.sh"
      ]
    volumes:
      - ${LOCAL_PROJECT_ROOT}:${CONTAINER_PROJECT_ROOT}
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "127.0.0.1:8888:8888"
      - "127.0.0.1:${CONTAINER_SSH_PORT}:22"
    init: true
    stdin_open: true
    tty: true